config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root to: 'feed#feed', as: 'feed'

  resources :recipes do
      resources :uploads, only: [:new, :create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe

    after_create :pluralize

    def pluralize
      @ingredient = self

      if @ingredient.measurement > 1
        @ingredient.measurement_type << "s"
        @ingredient.save!
      end
    end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  # require 'nokogiri'
  # require 'open-uri'
  has_many :ingredients
  has_many :uploads, dependent: :destroy

  mount_uploader :photo, ImageUploader

  # accepts_nested_attributes_for :uploads, allow_destroy: true

  # scope :with_upload, -> { joins(:uploads).group('recipes.id') }


  after_create :set_total_time
  # after_create :set_photo

  def set_total_time
    @recipe = self

    @recipe.total_time = @recipe.prep_time + @recipe.cooking_time

    @recipe.save!
  end

  # def set_photo
  #   if @recipe.photo.nil?
  #     url = URI.parse("https://pixabay.com/en/photos/?q=#{@recipe.name}&hp=&image_type=all&order=popular&cat=&min_width=&min_height=")
  #     page = Nokogiri::HTML(open(url)).xpath("//img/@src").first

  #     @recipe.photo = page

  #     @recipe.save!
  #   end
  # end


end

app/models/upload.rb
class Upload < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :recipe

  before_destroy :delete_cloudinary_asset

  def delete_cloudinary_asset
    if self.image?
      Cloudinary::Uploader.destroy(image.my_public_id)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  mount_uploader :profile_picture, ImageUploader

  has_many :recipes

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    attributes = [:profile_picture]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end
end

app/controllers/feed_controller.rb
class FeedController < ApplicationController
  def feed
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, except: [:new, :create, :index]

  def index
    @recipes = current_user.recipes
  end

  def edit
  end

  def update
    if @recipe.update_attributes(recipe_params)
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = "Unable to update recipe. #{@recipe.errors.full_messages.to_sentence}"
      redirect_to :edit
    end
  end


  def show
    @creator = User.find(@recipe.user_id)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.build(recipe_params)

    if @recipe.save
      # flash[:success] = "Your recipe was created. Now add some images."
      redirect_to feed_path(@recipe)
    else
      flash[:alert] = @recipe.errors.full_messages.to_sentence
      render :new
    end
  end

  private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :photo, :prep_time, :cooking_time, :short_description, :description)
  end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_user!
  # before_action :find_user, except: [:destroy]
  before_action :find_recipe

  def new
    @upload = @recipe.uploads.build
  end

  def create
      if params[:upload][:image]
        params[:upload][:image].each do |_, url|
          @recipe.uploads.create(image: url)
        end

        flash[:success] = "Upload successful."

        redirect_to recipe_path(@recipe)
      end
  end

  def destroy
    @upload = Upload.find(params[:id])
    authorize @upload

    if @upload.destroy
      redirect_to recipe_path(@recipe)
      flash[:success] = "Upload was deleted."
    else
      flash[:alert] = "Unable to delete upload."
    end
  end

  private

  def upload_params
    params.require(:upload).permit(:id, :image)
  end

  def find_recipe
    @recipe = Recipe.find(params[:recipe_id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def find_user
      @user = User.find(params[:id])
      authorize @user
  end

private

    # Modified Devise params for user login
    def sign_up_params
      params.require(:user).permit(:email, :password, :password_confirmation, :rememberable)
    end

    def after_sign_up_path_for(resource)
      edit_user_path(@user)
    end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/feed/feed.html.erb
<div class="col-xs-12 feed-container">

    <div class="col-xs-3 recipe-scroll">
      <% @recipes.each do |recipe| %>
        <%= link_to recipe_path(recipe), remote: true do%>
            <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<% if recipe.photo %>
                              <%= recipe.photo %>
                          <%  else %>
                            https://images.unsplash.com/photo-1522204605090-c9a2ae146cb3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0147eeb73ae17cd12d9f3d9523ba01a6&auto=format&fit=crop&w=2091&q=80
                          <% end %>
                          );">
              <div class="card-category">Recipe</div>
              <div class="card-description">
                  <h2><%= recipe.name%></h2>
                  <p>Total Cooking Time: <%= recipe.total_time%> Minutes</p>
              </div>
              <%= cl_image_tag(User.find(recipe.user_id).profile_picture, :class => "card-user") %>
            </div>
        <% end %>
      <% end %>


    </div>

    <div class="col-xs-9 recipe-show">


    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EatCheap</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

  </head>

  <body>
    <%= render partial: "partials/nav"%>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        Eat Cheap
      </a>

    </div>
    <% if current_user.nil? %>
      <div class="collapse navbar-collapse" id="bs-nav-demo">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <%= link_to "Sign Up", new_user_registration_path %>
          </li>
          <li>
            <%= link_to "Sign In", new_user_session_path %>
          </li>
        </ul>
      </div>
    <% else %>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Options
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit Profile", edit_user_registration_path(@user), class: "dropdown-item" %>
                <%= link_to "My Recipes", recipes_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
                <%= link_to "Create a New Recipe", new_recipe_path, class: "dropdown-item" %>
            </div>
          </li>
          <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                  Sign Out
              <% end %>
          </li>
        </ul>
      </div>
    <% end %>
    <!-- Collect the nav links, forms, and other content for toggling --><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/recipe/_recipe.html.erb
<%= @recipe.name %>
<%= @recipe.description %>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <div class="recipe-form">
    <div class="row">
      <div class="col-sm-12 col-md-4">
        <%= f.label :name, "Name"%>
      </div>
      <div class="col-sm-12 col-md-8">
        <%= f.text_field :name %>
        <p style="opacity:.4"><i>(Required)</i></p>
      </div>
    </div>
  <br>
    <div class="row">
      <div class="col-sm-12 col-md-4">
        <%= f.label :prep_time, "Prep Time" %>
      </div>
      <div class="field">
        <%= f.number_field :prep_time %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-4">
        <%= f.label :cooking_time, "Cooking Time" %>
      </div>
      <div class="field">
        <%= f.number_field :cooking_time %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-2">
        <%= f.label :short_description, "Short Description" %>
      </div>
      <div class="col-sm-12 col-md-10">
        <%= f.text_area :short_description, rows: 5, cols: 30 %>
      </div>
    </div>
  <br>
  <div class="row">
    <div class="col-sm-12 col-md-2">
      <%= f.label :description, "Description" %>
    </div>
    <div class="col-sm-12 col-md-10">
      <%= f.text_area :description, rows: 5, cols: 30 %>
    </div>
  </div>
  <br>
  <div class="field">
        <%= f.label :photo, "Add a Photo", :class => 'name' %>
        <%= f.cl_image_upload(:photo, return_delete_token: true) %>
        <p style="opacity:.4"><i>File Types: jpeg / png / gif<br>Max File-Size 20MB</i></p>
        </p>
    </div>
    <div class="col-xs-12">
        <div class="status"></div>
        <div class="preview"></div>
      </div>
          <%= cloudinary_js_config %>

  </div>
  <div class="row">
    <div class="col-xs-8 col-sm-6 col-md-4">
      <%= f.submit "Save", :class => 'btn btn-default btn-block' %>
    </div>
  </div>
<% end %>

app/views/recipes/_show.html.erb
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.6)), url(<% if @recipe.photo %>
                              <%= @recipe.photo %>
                          <%  else %>
                            https://images.unsplash.com/photo-1522204605090-c9a2ae146cb3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0147eeb73ae17cd12d9f3d9523ba01a6&auto=format&fit=crop&w=2091&q=80
                          <% end %>
                          ) no-repeat center center; background-size: 100% auto;">
  <h1><%=@recipe.name%></h1>
</div>
<div class="container col-xs-12">
  <div class="creator col-xs-12">
    <h4><strong>Created by: </strong><%=@creator.email%></h4>
  </div>
  <div class="times col-xs-12">
    <h4><strong>Prep Time: </strong><%=@recipe.prep_time%> minutes</h4>
    <h4><strong>Cook Time: </strong><%=@recipe.cooking_time%> minutes</h4>
  </div>
  <div class="ingredients col-xs-12">
    <h3>Ingredients:</h3>
    <% @recipe.ingredients.each do |ingredient| %>
      <h4><%=ingredient.measurement%> <%=ingredient.measurement_type%> of <%=ingredient.name%></h4>
    <% end %>
  </div>
  <div class="brief col-xs-12">
    <h2><%= @recipe.short_description %></h2>
  </div>
  <div class="description col-xs-12">
    <h4><%= @recipe.description%><h4>
  </div>
</div>

app/views/recipes/edit.html.erb
<% @page_title = "Edit Recipe" %>

<div class="container">
  <div class="row">
  <div class="col-sm-4">
  <h3><%= link_to "Edit Recipe Info", edit_recipe_path(@recipe) %></h3>
  <h3 style="opacity:.4"><%= link_to "Add Photos", new_recipe_upload_path(@recipe) %></h3>
  </div>
  <div class="col-sm-8">
  <%= render partial: "form", locals: {recipe: @recipe} %>
  </div>
  </div>
</div>

app/views/recipes/index.html.erb
<% @page_title = "Your Recipes" %>

<div class="container">
  <h3>Your Recipes</h3>
  </br>

  <%= link_to new_recipe_path, class: "btn btn-default" do %>
    Add Recipe
  <% end %>
  </br>
  </br>

  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th style="text-align: center;">Recipe Name</th>
        <th style="text-align: center;">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @recipes.each_with_index do |recipe, index| %>
        <tr>
          <th scope="row"><%= index + 1 %></th>
          <td><%= recipe.name %></td>
          <td style="text-align: center;">
            <%= link_to "View", feed_path(recipe) %>
            <%= link_to "Edit", edit_recipe_path(recipe) %>
            <%= link_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: 'Delete recipe and its uploads?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/recipes/new.html.erb
<% @page_title = "New Recipe" %>

<div class="container recipe-container">
  <h3>First, describe your recipe.</h3>

  <%= render partial: "form", locals: {recipe: @recipe} %>
</div>

app/views/recipes/show.html.erb
<div class="jumbotron jumbotron-fluid" style="background: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.6)), url(<% if @recipe.photo %>
                              <%= @recipe.photo %>
                          <%  else %>
                            https://images.unsplash.com/photo-1522204605090-c9a2ae146cb3?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=0147eeb73ae17cd12d9f3d9523ba01a6&auto=format&fit=crop&w=2091&q=80
                          <% end %>
                          ) no-repeat center center; background-size: 100% auto;">
  <h1><%=@recipe.name%></h1>
</div>
<div class="container col-xs-12">
  <div class="creator col-xs-12">
    <h4><strong>Created by: </strong><%=@creator.email%></h4>
  </div>
  <div class="times col-xs-12">
    <h4><strong>Prep Time: </strong><%=@recipe.prep_time%> minutes</h4>
    <h4><strong>Cook Time: </strong><%=@recipe.cooking_time%> minutes</h4>
  </div>
  <div class="ingredients col-xs-12">
    <h3>Ingredients:</h3>
    <% @recipe.ingredients.each do |ingredient| %>
      <h4><%=ingredient.measurement%> <%=ingredient.measurement_type%> of <%=ingredient.name%></h4>
    <% end %>
  </div>
  <div class="brief col-xs-12">
    <h2><%= @recipe.short_description %></h2>
  </div>
  <div class="description col-xs-12">
    <h4><%= @recipe.description%><h4>
  </div>
</div>

app/views/recipes/show.js.erb
$(".recipe-show").html("<%= j (render 'show') %>");

app/views/uploads/new.html.erb
<% @page_title = "Add Image" %>
<% content_for :footer_javascript do  %>
  <%= javascript_include_tag "upload" %>
<% end %>

<div class="container">
  <div class="row">
  <div class="col-sm-4">
  <h3 style="opacity:.4"><%= link_to "Edit Recipe Info", edit_recipe_path(@recipe) %></h3>
  <h3><%= link_to "Add Photos", new_recipe_upload_path(@recipe) %></h3>
  </div>

  <div class="col-sm-8">
  <%= form_for [@recipe, @upload], html:{multipart: true} do |f| %>
    <div>
      <div>
      <div class="col-sm-12 col-md-8">
        <%= f.cl_image_upload(:image, return_delete_token: true) %>
        <p style="opacity:.4"><i>File Types: jpeg / png / gif<br>Max File-Size 20MB</i></p>
        </p>
        <%= f.submit "Save", :class => 'btn btn-default btn-block top-10' %>
        <div class="top-10">- OR -</div>
        <div id="dropZone" class="top-10">
        <p>Drag/Drop Files Here</p>
        </div>
      </div>
  <% end %>

      <div class="col-xs-12 col-sm-6">
        <div class="status"></div>
        <div class="preview"></div>
      </div>


      </div>
    </div>
  </div>

    <%= cloudinary_js_config %>
  </div>
</div>

<script>
  $("#new_upload").on("submit", function (e) {
     // e.preventDefault();

     $("input[name='upload[image]']").each(function (index) {
          var inputName = $(this).attr('name');
          var inputNewName =  inputName +'[' + index + ']';
          $(this).attr('name', inputNewName);
          console.log($(this).val(), index)
     });

     // $(this).submit();
  });
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>